language: rust

rust:
- nightly

deploy:
  provider: gae
  keyfile: ~/rusty-bot-109e4ec25dbd.json
  project: rusty-bot
  skip_cleanup: true
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_38e93b3f580e_key -iv $encrypted_38e93b3f580e_iv
  -in rusty-bot-109e4ec25dbd.json.enc -out ~/rusty-bot-109e4ec25dbd.json
  -d
